name: Terraform CI/CD for GCP (Key-based)
 
on:
  push:
    branches: [ main ]
 
permissions:
  contents: read
 
jobs:
  terraform:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      # Authenticate via service account key JSON
      - name: Authenticate to Google Cloud (Key JSON)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.6"
 
      - name: Terraform Init
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        run: terraform init
 
     # - name: Terraform Format
     #   run: terraform fmt -check
 
      - name: Terraform Validate
        run: terraform validate
 
      - name: Terraform Plan
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        run: terraform plan -input=false -out=tfplan
 
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        env:
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        run: terraform apply -auto-approve tfplan