name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    # 1 Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # 2 Install gcloud
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v1

    # 3 Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6
    
    # 4 Authenticate to Google Cloud
    - name: Authenticate to GCP
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > key.json
        export GOOGLE_APPLICATION_CREDENTIALS=$PWD/key.json
        gcloud auth activate-service-account --key-file=key.json
        gcloud config set project project-610c3ab2-3496-44d6-b0b  
    
    # 5 Terraform Init
    - name: Terraform Init
    env:
      GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      run: terraform init

    # 6 Terraform Validate  
    - name: Terraform Validate
      run: terraform validate

    # 7 Terraform Plan (CREATE tfplan)
    - name: Terraform Plan 
      run: terraform plan -out=tfplan
    
    # 8 Terraform Apply (USE tfplan)
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve tfplan
